export default {
    "contentType":null,
    "properties":null,
    "offer":[
        {
            "properties":{
                "name":"",
                "category":"",
                "description":"",
                "productName":"",
                "retailerUrl":"",
                "productBrand":"",
                "reducedPrice":{
                    "amount":0,
                    "currencyCode":""
                },
                "originalPrice":{
                    "amount":0,
                    "currencyCode":""
                },
                "productImagePointer":{
                    "itemName":""
                }
            }
        }
    ]
}